# Location of input data
input_data:
  path_audio: '../../audio/'

# Configuration parameters related to the preprocessing workflow
preprocessing:
  path_save_metadata_full: '../../output/metadata/metadata_full.csv'
  path_save_metadata_sample: '../../output/metadata/metadata_sample.csv'
  sample_len: 5  # length of sample to build long soundscapes
  sample_period: '30T'
  date_range: ['2023-05-01', '2023-05-02']
  path_save_timelapse: '../../output/figures/'

# Configuration parameters related to the acoustic indices workflow
acoustic_indices:
  target_fs: 48000  # sampling rate for analysis
  group_by_site: True
  n_jobs: -1

# Configuration parameters related to the graphical soundscapes workflow
graph_soundscapes:
  target_fs: 48000  # target sampling frequency
  nperseg: 256  # window size to compute the spectrogram
  noverlap: 0  # overlap between windows to compute the spectrogram
  db_range: 80  # dB range for the spectrogram
  min_distance: 5  # minimum distance between peaks
  threshold_abs: -50  # threshold for detecting peaks
  group_by_site: True
  n_jobs: -1
