# Location of input data
input_data:
  path_audio: '../../audio/'

# Configuration parameters related to the preprocessing workflow
preprocessing:
  path_save_metadata_full: '../../output/metadata/metadata_full.csv'
  path_save_metadata_clean: '../../output/metadata/metadata_clean.csv'
  path_save_metadata_sample: '../../output/metadata/metadata_sample.csv'

# Configuration parameters related to the acoustic indices workflow
acoustic_indices:
  path_save_df: '../../output/dataframes_ai/'
  path_save_fig: '../../output/figures/'  # location to save the figure
  target_fs: 48000  # sampling rate for analysis

# Configuration parameters related to the graphical soundscapes workflow
graph_soundscapes:
  path_save_gs: '../../output/dataframes_gs/'  # location to save the dataframe
  path_save_fig: '../../output/figures/'  # location to save the figure
